import {
  MARCH_7TH_SKILL_PROFILE,
} from "./skill-profile";
import type { CompanionData } from "./types";

const PREVIEW_NOW = "2026-07-24T08:00:00.000Z";

/**
 * 非 Electron 环境只用于检查渲染布局，不写入磁盘，也不参与正式 Demo。
 */
export function createRendererPreviewData(): CompanionData {
  return {
    schemaVersion: 1,
    isDemoData: true,
    createdAt: PREVIEW_NOW,
    updatedAt: PREVIEW_NOW,
    demoNow: PREVIEW_NOW,
    demoStartedAt: PREVIEW_NOW,
    demoScenarioId: "japan_story",
    skill: structuredClone(MARCH_7TH_SKILL_PROFILE),
    profile: {
      id: "renderer-preview-player",
      displayName: "界面预览玩家",
      region: "japan",
      language: "zh-CN",
      timeZone: "Asia/Tokyo",
      playerType: ["story", "character_relationship"],
      selectedCharacterId: "march-7th",
      allowedContentTypes: [
        "daily",
        "photo",
        "postcard",
        "relationship",
        "version_preheat",
        "version_launch",
        "version_sustain",
      ],
      reducedContentTypes: [],
      proactiveContactEnabled: true,
      recallEnabled: false,
      personalizationEnabled: true,
      memoryEnabled: true,
      quietHours: {
        start: "22:00",
        end: "09:00",
      },
      weeklyContactLimit: 2,
      onboardingCompleted: false,
      consentVersion: "rehoyo-companion-consent-v1",
    },
    relationship: {
      playerId: "renderer-preview-player",
      characterId: "march-7th",
      relationshipStage: "new",
      joinedAt: "2026-07-10T08:00:00.000Z",
      lastInteractionAt: "2026-07-23T08:00:00.000Z",
      proactiveContactEnabled: true,
      allowedContentTypes: [
        "daily",
        "photo",
        "postcard",
        "relationship",
        "version_preheat",
        "version_launch",
        "version_sustain",
      ],
      reducedContentTypes: [],
      personalizationEnabled: true,
      memoryEnabled: true,
      quietHours: {
        start: "22:00",
        end: "09:00",
      },
      weeklyContactLimit: 2,
      ignoredCount: 0,
      consentVersion: "rehoyo-companion-consent-v1",
      activeCampaignIds: ["campaign-preview-march7th"],
      paused: false,
    },
    memories: [
      {
        id: "preview-memory-photo",
        playerId: "renderer-preview-player",
        characterId: "march-7th",
        type: "photo",
        title: "一起拍下的第一张照片",
        summary: "在普通的一天里，停下来拍了一张同行照片。",
        characterText:
          "普通的一天也值得留张照片嘛。以后翻到这一页，肯定会想起现在的心情。",
        createdAt: "2026-07-17T08:00:00.000Z",
        reusableByCharacter: true,
        userConfirmed: true,
        sourceEventId: "preview-event-photo",
        visual: {
          assetId: "march7th-static-concept-v1",
          alt: "三月七挥手邀请玩家一起拍照",
        },
      },
      {
        id: "preview-memory-choice",
        playerId: "renderer-preview-player",
        characterId: "march-7th",
        type: "choice",
        title: "下一次旅行的约定",
        summary: "下一次一起旅行时，想拍很多照片。",
        characterText:
          "说好啦，下次碰见漂亮的风景，咱可要拉着你多拍几张！",
        createdAt: "2026-07-11T08:00:00.000Z",
        reusableByCharacter: true,
        userConfirmed: true,
        sourceEventId: "preview-event-choice",
        visual: {
          assetId: "march7th-static-concept-v1",
          alt: "三月七举着相机，记下第一次同行约定",
        },
      },
    ],
    events: [],
    messages: [
      {
        id: "preview-message-campaign-review",
        characterId: "march-7th",
        playerId: "renderer-preview-player",
        type: "version_launch",
        title: "概念版本 · 已经开启",
        body: "来啦来啦！概念版本已在2026年8月7日 10:00（模拟）开启，奖励信息仅为模拟占位，不代表真实游戏内容。要不要和咱一起去看看？",
        createdAt: PREVIEW_NOW,
        eventId: "preview-event-campaign-launch",
        campaignId: "campaign-preview-march7th",
        reviewStatus: "awaiting_human_review",
        automaticReview: {
          checkedAt: PREVIEW_NOW,
          passed: true,
          checks: [
            {
              id: "fixed-facts-trace",
              label: "固定事实引用有效",
              status: "pass",
              detail: "消息只引用当前任务锁定的固定事实。",
            },
            {
              id: "persona-boundary",
              label: "角色表达符合边界",
              status: "pass",
              detail: "表达使用同伴式短句，没有 AI 或客服话术。",
            },
          ],
        },
        trace: {
          skillVersion: MARCH_7TH_SKILL_PROFILE.skillVersion,
          templateId: "march7th-version-invitation-v1",
          ruleIds: [
            "knowledge.fixed_facts_only",
            "memory.authorized_reference",
            "campaign.single_call_to_action",
          ],
          fixedFactIds: [
            "fact-dataNature",
            "fact-versionName",
            "fact-eventTime",
            "fact-actionTarget",
            "fact-rewardStatement",
          ],
          memoryIds: ["preview-memory-photo"],
          generatedAt: PREVIEW_NOW,
        },
        deliveryMode: "proactive",
        favorite: false,
        liked: false,
        remindLater: false,
        action: {
          label: "打开模拟版本页",
          kind: "open_version_demo",
          targetId:
            "product://campaign/campaign-preview-march7th",
        },
      },
      {
        id: "preview-message-daily",
        characterId: "march-7th",
        playerId: "renderer-preview-player",
        type: "daily",
        title: "列车窗边的小休息",
        body: "忙完啦？先歇一小会儿。咱刚把照片翻到一半，正好给你留了个位置。",
        createdAt: "2026-07-23T08:00:00.000Z",
        eventId: "preview-event-daily",
        reviewStatus: "approved",
        trace: {
          skillVersion: MARCH_7TH_SKILL_PROFILE.skillVersion,
          templateId: "march7th-daily-checkin-v1",
          ruleIds: [
            "behavior.short_companion_reply",
            "relationship.low_interruption",
          ],
          fixedFactIds: [],
          memoryIds: [],
          generatedAt: "2026-07-23T08:00:00.000Z",
        },
        sentAt: "2026-07-23T08:00:00.000Z",
        deliveryMode: "proactive",
        favorite: false,
        liked: false,
        remindLater: false,
      },
      {
        id: "preview-message-photo",
        characterId: "march-7th",
        playerId: "renderer-preview-player",
        type: "photo",
        title: "第一张同行照片",
        body: "普通的一天也值得拍下来嘛。喏，这张咱可替你好好收进相册啦！",
        createdAt: "2026-07-17T08:00:00.000Z",
        eventId: "preview-event-photo",
        reviewStatus: "approved",
        trace: {
          skillVersion: MARCH_7TH_SKILL_PROFILE.skillVersion,
          templateId: "march7th-photo-memory-v1",
          ruleIds: [
            "behavior.photo_first",
            "memory.explicit_confirmation",
          ],
          fixedFactIds: [],
          memoryIds: ["preview-memory-photo"],
          generatedAt: "2026-07-17T08:00:00.000Z",
        },
        sentAt: "2026-07-17T08:00:00.000Z",
        deliveryMode: "proactive",
        readAt: "2026-07-17T08:00:00.000Z",
        favorite: true,
        liked: true,
        remindLater: false,
        action: {
          label: "查看共同相册",
          kind: "open_album",
          targetId: "preview-memory-photo",
        },
      },
    ],
    campaigns: [
      {
        id: "campaign-preview-march7th",
        characterId: "march-7th",
        version: "概念版本",
        region: "japan",
        targetSegments: ["story", "character_relationship"],
        objective: "launch",
        globalTheme: "与三月七继续一段新的模拟旅程",
        sellingPoints: ["一段新的模拟旅程"],
        narrativeApproach: "从玩家允许引用的共同照片切入。",
        fixedFacts: {
          dataNature: "全部内容均为产品内模拟数据",
          versionName: "概念版本",
          eventTime: "2026年8月7日 10:00（模拟）",
          actionTarget:
            "product://campaign/campaign-preview-march7th",
          rewardStatement:
            "奖励信息仅为模拟占位，不代表真实游戏内容",
        },
        fixedFactEntries: [
          {
            id: "fact-dataNature",
            key: "dataNature",
            label: "数据性质",
            value: "全部内容均为产品内模拟数据",
            source: "product_rule",
            locked: true,
            reviewedAt: PREVIEW_NOW,
          },
          {
            id: "fact-versionName",
            key: "versionName",
            label: "活动名称",
            value: "概念版本",
            source: "sandbox_input",
            locked: true,
            reviewedAt: PREVIEW_NOW,
          },
          {
            id: "fact-eventTime",
            key: "eventTime",
            label: "活动时间",
            value: "2026年8月7日 10:00（模拟）",
            source: "sandbox_input",
            locked: true,
            reviewedAt: PREVIEW_NOW,
          },
          {
            id: "fact-actionTarget",
            key: "actionTarget",
            label: "安全入口",
            value: "product://campaign/campaign-preview-march7th",
            source: "product_rule",
            locked: true,
            reviewedAt: PREVIEW_NOW,
          },
          {
            id: "fact-rewardStatement",
            key: "rewardStatement",
            label: "奖励说明",
            value: "奖励信息仅为模拟占位，不代表真实游戏内容",
            source: "sandbox_input",
            locked: true,
            reviewedAt: PREVIEW_NOW,
          },
        ],
        allowedMemoryTypes: ["choice", "photo"],
        schedule: [
          {
            id: "campaign-preview-d14",
            phase: "preheat",
            scheduledAt: PREVIEW_NOW,
            templateId: "march7th-version-preheat-v1",
          },
          {
            id: "campaign-preview-d0",
            phase: "launch",
            scheduledAt: "2026-08-07T08:00:00.000Z",
            templateId: "march7th-version-invitation-v1",
          },
          {
            id: "campaign-preview-d7",
            phase: "sustain",
            scheduledAt: "2026-08-14T08:00:00.000Z",
            templateId: "march7th-version-sustain-v1",
          },
          {
            id: "campaign-preview-d42",
            phase: "complete",
            scheduledAt: "2026-09-18T08:00:00.000Z",
            templateId: "campaign-complete-v1",
          },
        ],
        generationMode: "template_variables",
        frequencyLimit: "版本周期最多一次召回。",
        reviewRequired: true,
        expandConditions: ["人工批准", "自动检查通过"],
        throttleConditions: ["玩家忽略", "接近频率上限"],
        stopConditions: ["玩家退订", "事实校验失败"],
        automaticReview: {
          checkedAt: PREVIEW_NOW,
          passed: true,
          checks: [
            {
              id: "fixed-facts-present",
              label: "固定事实完整",
              status: "pass",
              detail: "活动名、时间、入口、奖励和数据性质均已提供。",
            },
            {
              id: "schedule-coverage",
              label: "发行阶段完整",
              status: "pass",
              detail: "排期覆盖 D-14、D0、持续期和结束阶段。",
            },
          ],
        },
        humanReview: {
          reviewer: "界面预览审核员",
          decision: "approved",
          reviewedAt: PREVIEW_NOW,
          note: "用于检查发行沙盒运行状态。",
        },
        status: "running",
      },
    ],
    executionLog: [
      {
        id: "preview-log-scenario",
        occurredAt: PREVIEW_NOW,
        category: "system",
        action: "demo_scenario_loaded",
        summary: "已载入日本剧情玩家本地演示案例。",
        actor: "system",
        entityType: "profile",
        entityId: "renderer-preview-player",
        metadata: {
          scenarioId: "japan_story",
          isDemoData: true,
        },
      },
      {
        id: "preview-log-campaign",
        occurredAt: PREVIEW_NOW,
        category: "campaign",
        action: "campaign_start",
        summary: "发行任务开始运行。",
        actor: "reviewer",
        entityType: "campaign",
        entityId: "campaign-preview-march7th",
        metadata: {
          status: "running",
        },
      },
      {
        id: "preview-log-review",
        occurredAt: PREVIEW_NOW,
        category: "review",
        action: "scheduled_message_awaiting_human_review",
        summary: "排期生成的消息通过自动检查，等待人工审核。",
        actor: "system",
        entityType: "message",
        entityId: "preview-message-campaign-review",
        metadata: {
          phase: "launch",
          failedChecks: 0,
          sent: false,
        },
      },
    ],
  };
}
